ci: update workflow config

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -43,13 +43,14 @@ defaults:
   run:
     shell: bash
 
+
 jobs:
 
   ###########################################################
-  build:
+  maven-build:
   ###########################################################
     runs-on: ubuntu-latest
-    concurrency: ci-${{ github.ref }}-${{ matrix.target-platform }}
+    concurrency: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.target-platform }}
 
     env:
       JAVA_VERSION: ${{ matrix.java-version }}
@@ -66,7 +67,13 @@ jobs:
             java-version: 21
 
     steps:
-    - name: Show environment variables
+    - name: "Show: GitHub context"
+      env:
+        GITHUB_CONTEXT: ${{ toJSON(github) }}
+      run: echo $GITHUB_CONTEXT
+
+
+    - name: "Show: environment variables"
       run: env | sort
 
 
@@ -75,14 +82,24 @@ jobs:
 
 
     - name: Configure fast APT repository mirror
+      if: runner.os == 'Linux'
       uses: vegardit/fast-apt-mirror.sh@v1
 
 
-    - name: "Install: xvfb"
-      run: sudo apt-get install -y xvfb
+    - name: "Install: Linux packages 📦"
+      run: |
+        set -eux
+        sudo apt-get install --no-install-recommends -y xvfb
+
+        # prevents: "Failed to execute child process “dbus-launch” (No such file or directory)"
+        sudo apt-get install --no-install-recommends -y dbus-x11
+
+        # prevents: "dbind-WARNING **: 20:17:55.046: AT-SPI: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files"
+        # see https://gist.github.com/jeffcogswell/62395900725acef1c0a5a608f7eb7a05
+        sudo apt-get install --no-install-recommends -y at-spi2-core
 
 
-    - name: "Install: JDK ${{ env.JAVA_VERSION }}"
+    - name: "Install: JDK ${{ env.JAVA_VERSION }} ☕"
       uses: actions/setup-java@v4  # https://github.com/actions/setup-java
       with:
         distribution: temurin
@@ -92,9 +109,10 @@ jobs:
     - name: "Cache: Local Maven Repository"
       uses: actions/cache@v4
       with:
-        # Excluded sub directory not working https://github.com/actions/cache/issues/494#issuecomment-948783891
+        # Excluded sub directory not working https://github.com/actions/toolkit/issues/713
         path: |
           ~/.m2/repository/*
+          !~/.m2/repository/com/vegardit/no-npe
           !~/.m2/repository/.cache/tycho
           !~/.m2/repository/.meta/p2-artifacts.properties
           !~/.m2/repository/p2
@@ -115,10 +133,10 @@ jobs:
     - name: "Install: Maven"
       uses: stCarolas/setup-maven@v5  # https://github.com/stCarolas/setup-maven
       with:
-        maven-version: 3.9.6
+        maven-version: 3.9.7
 
 
-    - name: Build with Maven
+    - name: "Build with Maven 🔨"
       continue-on-error: ${{ matrix.target-platform == 'unstable' }}
       id: maven-build
       env:
@@ -132,12 +150,11 @@ jobs:
         git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
 
         MAVEN_OPTS="${MAVEN_OPTS:-}"
-        MAVEN_OPTS="$MAVEN_OPTS -XX:+TieredCompilation -XX:TieredStopAtLevel=1" # https://zeroturnaround.com/rebellabs/your-maven-build-is-slow-speed-it-up/
-        MAVEN_OPTS="$MAVEN_OPTS -Djava.security.egd=file:/dev/./urandom" # https://stackoverflow.com/questions/58991966/what-java-security-egd-option-is-for/59097932#59097932
-        MAVEN_OPTS="$MAVEN_OPTS -Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss,SSS" # https://stackoverflow.com/questions/5120470/how-to-time-the-different-stages-of-maven-execution/49494561#49494561
-        MAVEN_OPTS="$MAVEN_OPTS -Xmx1024m -Djava.awt.headless=true -Djava.net.preferIPv4Stack=true -Dhttps.protocols=TLSv1.2"
-        echo "  -> MAVEN_OPTS: $MAVEN_OPTS"
+        MAVEN_OPTS+=" -Djava.security.egd=file:/dev/./urandom" # https://stackoverflow.com/questions/58991966/what-java-security-egd-option-is-for/59097932#59097932
+        MAVEN_OPTS+=" -Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss,SSS" # https://stackoverflow.com/questions/5120470/how-to-time-the-different-stages-of-maven-execution/49494561#49494561
+        MAVEN_OPTS+=" -Xmx1024m -Djava.awt.headless=true -Djava.net.preferIPv4Stack=true -Dhttps.protocols=TLSv1.3,TLSv1.2"
         export MAVEN_OPTS
+        echo "MAVEN_OPTS: $MAVEN_OPTS"
 
         # prevent "org.eclipse.swt.SWTError: No more handles [gtk_init_check() failed]"
         xvfb-run mvn \
@@ -271,7 +288,7 @@ jobs:
 
 
     - name: "SSH session for debugging: start"
-      uses: mxschmitt/action-tmate@v3 # https://github.com/mxschmitt/action-tmate
+      uses: mxschmitt/action-tmate@v3  # https://github.com/mxschmitt/action-tmate
       if: always() && steps.DEBUG_SSH_SESSSION_CHECK.outputs.start_ssh_session
       with:
         limit-access-to-actor: ${{ inputs.debug-with-ssh-only-for-actor }}
@@ -280,7 +297,7 @@ jobs:
   ###########################################################
   dependabot-pr-auto-merge:
   ###########################################################
-    needs: build
+    needs: maven-build
     if: ${{ github.event_name == 'pull_request' && github.actor == 'dependabot[bot]' }}
     runs-on: ubuntu-latest
 
