update build config

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -8,6 +8,7 @@ on:
     tags-ignore:
     - '**'
     paths-ignore:
+    - '**/*.adoc'
     - '**/*.md'
     - '.github/*.yml'
   pull_request:
@@ -32,31 +33,53 @@ jobs:
     runs-on: ubuntu-latest
     concurrency: ci-${{ github.ref }}
     steps:
+    - name: Show environment variables
+      run: env | sort
 
     - name: Git Checkout
       uses: actions/checkout@v3 #https://github.com/actions/checkout
 
-    - name: Set up JDK ${{ env.JAVA_VERSION }}
+
+    - name: Configure APT
+      run: |
+        # Workaround to avoid sporadic connectivity issues "Could not connect to azure.archive.ubuntu.com:80"
+        # see https://github.com/actions/virtual-environments/issues/675
+        echo 'APT::Acquire::Retries "3";' | sudo tee /etc/apt/apt.conf.d/80-acquire-retries
+        if ! curl --max-time 3 --output /dev/null --silent --head --fail "http://azure.archive.ubuntu.com/ubuntu/dists/"; then
+          sudo sed -i 's/azure\.//' /etc/apt/sources.list
+        fi
+
+        echo 'APT::Install-Recommends "0";'  | sudo tee /etc/apt/apt.conf.d/01-norecommends
+        echo 'APT::Install-Suggests "0";' | sudo tee -a /etc/apt/apt.conf.d/01-norecommends
+
+        # avoid potential 404 see https://github.com/actions/runner-images/issues/592
+        sudo apt-get update 
+
+
+    - name: "Install: xvfb"
+      run: sudo apt-get install -y xvfb
+
+
+    - name: "Install: JDK ${{ env.JAVA_VERSION }}"
       uses: actions/setup-java@v3 # https://github.com/actions/setup-java
       with:
-        distribution: microsoft # not using temurin, zulu which seems to miss Let's Encrypt root ca in truststore
+        distribution: temurin
         java-version: ${{ env.JAVA_VERSION }}
 
-    - name: Install xvfb
-      run: sudo apt-get install -o Acquire::Retries=3 --no-install-recommends -y xvfb
 
-    - name: "Cache: Local Maven Repository"
-      uses: actions/cache@v3
+    - name: "Cache: Restore"
+      id: cache-restore
+      if: ${{ !env.ACT }} # https://github.com/nektos/act#skipping-steps
+      uses: actions/cache/restore@v3
       with:
         path: |
           ~/.m2/repository
           !~/.m2/repository/.cache/tycho/https/raw.githubusercontent.com
           !~/.m2/repository/*SNAPSHOT*
-        key: ${{ runner.os }}-mvnrepo-${{ hashFiles('build.target') }}-${{ hashFiles('**/pom.xml') }}
-        restore-keys: |
-          ${{ runner.os }}-mvnrepo-${{ hashFiles('build.target') }}
+        key: ${{ runner.os }}-${{ hashFiles('build.target') }}-${{ hashFiles('**/pom.xml') }}
 
-    - name: Set up Maven
+
+    - name: "Install: Maven"
       uses: stCarolas/setup-maven@v4.5 # https://github.com/stCarolas/setup-maven
       with:
         maven-version: 3.8.6
@@ -98,7 +121,7 @@ jobs:
 
 
     - name: "Delete previous 'latest' release"
-      if: github.ref == 'refs/heads/main'
+      if: ${{ github.ref == 'refs/heads/main' && !env.ACT }}
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       run: |
@@ -122,7 +145,7 @@ jobs:
 
 
     - name: "Create 'latest' release"
-      if: github.ref == 'refs/heads/main'
+      if: ${{ github.ref == 'refs/heads/main' && !env.ACT }}
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       run: |
@@ -136,7 +159,7 @@ jobs:
 
 
     - name: Deploy p2 update site
-      if: github.ref == 'refs/heads/main'
+      if: ${{ github.ref == 'refs/heads/main' && !env.ACT }}
       run: |
         set -eux
 
@@ -178,16 +201,9 @@ jobs:
         git push origin updatesite --force
 
 
-    - name: "Delete intermediate build artifacts"
-      uses: geekyeggo/delete-artifact@v2 # https://github.com/GeekyEggo/delete-artifact/
-      with:
-        name: "*"
-        failOnError: false
-
-
     - name: Generate GitHub Access Token
       uses: tibdex/github-app-token@v1 # https://github.com/tibdex/github-app-token
-      if: github.ref == 'refs/heads/main'
+      if: ${{ github.ref == 'refs/heads/main' && !env.ACT }}
       id: generate_token
       # see https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#authenticating-with-github-app-generated-tokens
       with:
@@ -196,8 +212,8 @@ jobs:
         private_key: ${{ secrets.DART4E_TU_PRIVATE_KEY }}
 
 
-    - name: Trigger Dart4E Studio Build
-      if: github.ref == 'refs/heads/main'
+    - name: Trigger Haxe Studio Build
+      if: ${{ github.ref == 'refs/heads/main' && !env.ACT }}
       run: |
         curl --fail \
           -H"Authorization: Bearer ${{ steps.generate_token.outputs.token }}" \
@@ -206,3 +222,26 @@ jobs:
           -XPOST \
           https://api.github.com/repos/dart4e/dart4e-studio/dispatches \
           --data '{"event_type": "new-dart4e-release"}'
+
+
+    ##################################################
+    # Cache Update
+    # See https://github.com/actions/cache/issues/342
+    ##################################################
+    - name: "Cache: Delete Previous"
+      if: ${{ steps.cache-restore.outputs.cache-hit && !env.ACT }}
+      env:
+        GH_TOKEN: ${{ github.token }}
+      run: |
+        gh extension install actions/gh-actions-cache
+        gh actions-cache delete ${{ steps.cache-restore.outputs.cache-primary-key }} --confirm
+
+    - name: "Cache: Update"
+      uses: actions/cache/save@v3
+      if: ${{ always() && !env.ACT }} # save cache even fails
+      with:
+        path: |
+          ~/.m2/repository
+          !~/.m2/repository/.cache/tycho/https/raw.githubusercontent.com
+          !~/.m2/repository/*SNAPSHOT*
+        key: ${{ steps.cache-restore.outputs.cache-primary-key }}
